apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: ocp-prod01-fbnvt
  name: ocp-prod01-fbnvt-worker-0
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-prod01-fbnvt
      machine.openshift.io/cluster-api-machineset: ocp-prod01-fbnvt-worker-0
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-prod01-fbnvt
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp-prod01-fbnvt-worker-0
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 200
          kind: VSphereMachineProviderSpec
          memoryMiB: 49152
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: VLAN_65
          numCPUs: 16
          numCoresPerSocket: 2
          snapshot: ""
          template: ocp-prod01-fbnvt-rhcos-generated-region-generated-zone
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: SHB Finance DC
            datastore: /SHB Finance DC/datastore/FC24
            folder: /SHB Finance DC/vm/ocp-prod01-fbnvt
            resourcePool: /SHB Finance DC/host/HA-Cluster1//Resources
            server: vcdc.shbfinance.com.vn
status:
  replicas: 0
