apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  creationTimestamp: null
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-ssh
spec:
  config:
    ignition:
      version: 3.2.0
    passwd:
      users:
      - name: core
        sshAuthorizedKeys:
        - |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHT0Go5nofYJa/hds6SVC+vOQQLLWyRY4qGRopU/i2aKNOIvqemVFwlRuH56jooCvvbBJdj3wFnEJLVIf2LVt+bNUiOPaAiMSHWYNWjlvOwlZbEGizw/Y0AlCYjD3Q/wn5d/bVPL9L/7yk5kdzRJDeRqBTJozJnG6ET6GslFe3j9XugGxTFRczpDureCjjMvzA35dw4fABq97os7aIKezhxRlDksxZu5yb982EOfaFnao84TGT4Vp2KMtnCMHU/0Hw50Bd+qf+EDKnjVoptEUlGq6hBrCq7RogeubXqLyLo73gabeUxtoz0hrJp3edVVk6q4Vg1RSajSvUC7twxfe0xQ9OtESp0zOQfgxHzaNHAWa3l5brONQvO0pO/pH8hMbUqUxuuzErZGTz606rNg+krb/3qoqgiqLTxaHvzETjMSJTtlwhQlJgxjFPEOROcbdzvsvHGEvEEamMFKde7dmYjSWzmocIqUcFOnxNlRewtfzY3yviKnNardWF6cWueRvJf1tsfeOnQHa8gTULgb0g9PNw83+WuNbV5hM1dsRYPkyKX4MgyWjWUnz3tjZpeKwEN6VBndWkHgsJCBlPTZEDoiIm4E76SeZ3GjSglNrHKxzk+YAm+wm0vrkxW4oMIfUCxgxCUR+woVUDOjgjUbCrlNZJAEeUgPfkYid3J2/DGQ== ocp@dc-ocp-bastion
  extensions: null
  fips: false
  kernelArguments: null
  kernelType: ""
  osImageURL: ""
