apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: ocp-prod01-fbnvt
    machine.openshift.io/cluster-api-machine-role: master
    machine.openshift.io/cluster-api-machine-type: master
  name: ocp-prod01-fbnvt-master-1
  namespace: openshift-machine-api
spec:
  lifecycleHooks: {}
  metadata: {}
  providerSpec:
    value:
      apiVersion: machine.openshift.io/v1beta1
      credentialsSecret:
        name: vsphere-cloud-credentials
      diskGiB: 200
      kind: VSphereMachineProviderSpec
      memoryMiB: 16384
      metadata:
        creationTimestamp: null
      network:
        devices:
        - networkName: VLAN_65
      numCPUs: 8
      numCoresPerSocket: 2
      snapshot: ""
      template: ocp-prod01-fbnvt-rhcos-generated-region-generated-zone
      userDataSecret:
        name: master-user-data
      workspace:
        datacenter: SHB Finance DC
        datastore: /SHB Finance DC/datastore/FC24
        folder: /SHB Finance DC/vm/ocp-prod01-fbnvt
        resourcePool: /SHB Finance DC/host/HA-Cluster1//Resources
        server: vcdc.shbfinance.com.vn
status: {}
