kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: vsphere-creds-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["vsphere-creds"]
  verbs: ["get"]
