apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: external
    namespace: openshift-ingress-operator
  spec:
    domain: shbfinance.com.vn
    endpointPublishingStrategy:
      type: HostNetwork
      hostNetwork:
        protocol: PROXY
        httpPort: 80
        httpsPort: 443
        statsPort: 1938
    nodePlacement:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra-ext
      - effect: NoExecute
        key: node-role.kubernetes.io/infra-ext
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/infra-ext: ""
          purpose: ext-router
    routeSelector:
      matchLabels:
        type: external
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
