apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: 480D7vU7dN1ksFzHi8AK
  access_key_secret: EkUr8tWSKzT5Si1hYN2e5TWPnKYIx6dHFzEGZYdt
  bucketnames: loki
  endpoint: http://dc-ocp-minio-api.shbfinance.com.vn

