apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: cluster
spec:
  domain: apps.ocp-prod01.shbfinance.com.vn
  loadBalancer:
    platform:
      type: ""
status:
  defaultPlacement: Workers
