apiVersion: v1
data:
  install-config: |
    additionalTrustBundlePolicy: Proxyonly
    apiVersion: v1
    baseDomain: shbfinance.com.vn
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform: {}
      replicas: 3
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform: {}
      replicas: 3
    metadata:
      creationTimestamp: null
      name: ocp-prod01
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      networkType: OVNKubernetes
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      vsphere:
        apiVIPs:
        - 10.0.65.7
        failureDomains:
        - name: generated-failure-domain
          region: generated-region
          server: vcdc.shbfinance.com.vn
          topology:
            computeCluster: /SHB Finance DC/host/HA-Cluster1
            datacenter: SHB Finance DC
            datastore: /SHB Finance DC/datastore/FC24
            networks:
            - VLAN_65
            resourcePool: /SHB Finance DC/host/HA-Cluster1//Resources
          zone: generated-zone
        ingressVIPs:
        - 10.0.65.8
        vcenters:
        - datacenters:
          - SHB Finance DC
          password: ""
          server: vcdc.shbfinance.com.vn
          user: ""
    publish: External
    pullSecret: ""
    sshKey: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHT0Go5nofYJa/hds6SVC+vOQQLLWyRY4qGRopU/i2aKNOIvqemVFwlRuH56jooCvvbBJdj3wFnEJLVIf2LVt+bNUiOPaAiMSHWYNWjlvOwlZbEGizw/Y0AlCYjD3Q/wn5d/bVPL9L/7yk5kdzRJDeRqBTJozJnG6ET6GslFe3j9XugGxTFRczpDureCjjMvzA35dw4fABq97os7aIKezhxRlDksxZu5yb982EOfaFnao84TGT4Vp2KMtnCMHU/0Hw50Bd+qf+EDKnjVoptEUlGq6hBrCq7RogeubXqLyLo73gabeUxtoz0hrJp3edVVk6q4Vg1RSajSvUC7twxfe0xQ9OtESp0zOQfgxHzaNHAWa3l5brONQvO0pO/pH8hMbUqUxuuzErZGTz606rNg+krb/3qoqgiqLTxaHvzETjMSJTtlwhQlJgxjFPEOROcbdzvsvHGEvEEamMFKde7dmYjSWzmocIqUcFOnxNlRewtfzY3yviKnNardWF6cWueRvJf1tsfeOnQHa8gTULgb0g9PNw83+WuNbV5hM1dsRYPkyKX4MgyWjWUnz3tjZpeKwEN6VBndWkHgsJCBlPTZEDoiIm4E76SeZ3GjSglNrHKxzk+YAm+wm0vrkxW4oMIfUCxgxCUR+woVUDOjgjUbCrlNZJAEeUgPfkYid3J2/DGQ== ocp@dc-ocp-bastion
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: The install-config content used to create the cluster.  The
      cluster configuration may have evolved since installation, so check cluster
      configuration resources directly if you are interested in the current cluster
      state.
  name: cluster-config-v1
  namespace: kube-system
