apiVersion: v1
kind: PersistentVolume
metadata:
  name: etherpad-pv
spec:
  storageClassName: "nfs-client"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
