apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data
    server: 10.0.65.100
  persistentVolumeReclaimPolicy: Recycle
